databases:
  - name: iform-quality-db
    plan: free
    postgresMajorVersion: 16

services:
  - type: web
    name: iform-quality-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: iform-quality-db
          property: connectionString
